apiVersion: apps/v1
kind: Deployment

metadata:
  name: expense-backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: expense-backend

  template:
    metadata:
      labels:
        app: expense-backend

    spec:
      containers:
        - name: expense-tracker-backend
          image: khalilart/expense-tracker-backend:latest

          ports:
            - containerPort: 4000

          env:
            - name: PORT
              value: "4000"

            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/expense_tracker"

            - name: JWT_SECRET
              value: "your-secret"
