version: "3.9"

services:
  db:
    image: postgres:15
    container_name: expense_tracker_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense_tracker

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - expense-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: expense_tracker_backend

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/expense_tracker?schema=public

    ports:
      - "4000:4000"

    networks:
      - expense-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: expense_tracker_frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - expense-network

volumes:
  postgres_data:

networks:
  expense-network:
    driver: bridge
