apiVersion: v1
kind: Service

metadata:
  name: expense-frontend-service

spec:
  type: NodePort

  selector:
    app: expense-frontend

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
